### ISSUE TITLE
[ ⚔️AnkiArcade ] Error when starting Anki sound, (Linux Manjaro)

### ISSUE THREAD

**Issue by shigeyukey** [shigeyukey/AnkiArcade#1]
from Victor Evangelista

----

Hi, man. can you help me?   its all okay, only when i open anki, sometimes i got an error, and i just want to get rid of it Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.6.32-1-MANJARO-x86_64-with-glibc2.39

Traceback (most recent call last):
  File "aqt.mpv", line 371, in _send_request
  File "aqt.mpv", line 352, in _get_response
aqt.mpv.MPVCommandError: invalid parameter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 219, in on_window_init
  File "_aqt.hooks", line 3553, in __call__
  File "/home/victorsilva/.local/share/Anki2/addons21/AnkiArcade/system_sound_effect.py", line 42, in anki_start_sound
    anki_play_sound("anki_Start")
  File "/home/victorsilva/.local/share/Anki2/addons21/AnkiArcade/system_sound_effect.py", line 38, in anki_play_sound
    av_player.play_file(audio_path)
  File "aqt.sound", line 170, in play_file
  File "aqt.sound", line 150, in play_tags
  File "aqt.sound", line 209, in _play_next_if_idle
  File "aqt.sound", line 216, in _play
  File "aqt.sound", line 431, in play
  File "aqt.mpv", line 593, in command
  File "aqt.mpv", line 373, in _send_request
aqt.mpv.MPVCommandError: ['loadfile', '/home/victorsilva/.local/share/Anki2/addons21/AnkiArcade/media/system_sounds/00_cyber/anki_Start/open menu 5.wav', 'replace', 'pause=no']: invalid parameter

----

hey, I notice when I use version 1.6.2 the progress bar works perfectly. in the newer versions from 1.6.3 ~ 1.7.0 i get some bugs. the bug is that message error with sounds. okay, i could remove ambient sounds no problems. but could you fix this bug, i need to open confg and click "okay", because it begins resized with low size, and when i open config and click okay, it comes back to normal. in this version, 1.6.2 I don't get these errors i'm talking about. by the way, loved your work!

**Comment by shigeyukey** [comment]
added try - except.
