### ISSUE TITLE
[ ⚔️AnkiArcade ] Addon doesnt work at all. anki starts with an error ( Linux )

### ISSUE THREAD

**Issue by shigeyukey** [shigeyukey/AnkiArcade#2]
[From Andreas China](https://www.patreon.com/posts/ankiarcade-1-7-0-101482750?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link)

----
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-5.15.0-107-generic-x86_64-with-glibc2.35

Traceback (most recent call last):
  File "aqt.main", line 1731, in onAppMsg
  File "aqt.main", line 1322, in installAddon
  File "aqt.addons", line 1657, in installAddonPackages
  File "aqt.addons", line 531, in processPackages
  File "aqt.addons", line 467, in install
  File "aqt.addons", line 510, in _install
  File "zipfile", line 1625, in extract
  File "zipfile", line 1696, in _extract_member
OSError: [Errno 36] Der Dateiname ist zu lang: '/home/user1/.local/share/Anki2/addons21/AnkiArcade/fluidsynth/01_Classic/Modest Mussorgsky, 00 Pictures at an Exhibition (1874) 07 Promenade - The Market Place of Limoges - Catacombae - Con mortuis in lingua mortua.mid'

**Comment by shigeyukey** [comment]
to short name.
